[package]
name = "hare-common-utils"
version = "0.1.0"
edition = "2021"

[features]
default = []
audit_log = ["dep:bon", "dep:chrono", "dep:tower-http", "dep:tower-layer", "dep:tower-service", "dep:tracing", "dep:valuable", "request_id"]
axum = ["audit_log", "dep:axum"]
header = ["dep:tower-layer", "dep:tower-service"]
request_id = ["dep:tower-http"]
tonic = ["audit_log", "dep:tonic"]

[dependencies]
axum = { workspace = true, default-features = false, features = ["http1", "http2", "tokio"], optional = true }
bon = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
http = { workspace = true }
tokio = { workspace = true, default-features = false }
tonic = { workspace = true, optional = true }
tower-http = { workspace = true, features = ["request-id"], optional = true }
tower-layer = { workspace = true, optional = true }
tower-service = { workspace = true, optional = true }
tracing = { workspace = true, features = [ "valuable" ], optional = true }
uuid = { workspace = true }
valuable = { workspace = true, features = [ "derive" ], optional = true }
