[package]
name = "hare-control-plane-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hare-common-utils = { path = "../hare-common-utils" }
hare-control-plane-model = { path = "../hare-control-plane-model" }
hare-control-plane-service = { path = "../hare-control-plane-service" }
hare-data-plane-client = { path = "../hare-data-plane-client", features = ["sqlite"] }
tokio = { workspace = true, features = [ "rt-multi-thread" ] }
tonic = { workspace = true }
tower-http = { workspace = true, features = ["request-id"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [ "env-filter" ] }