[package]
name = "hare-control-plane-client"
version = "0.1.0"
edition = "2021"

[dependencies]
hare-common-model = { path = "../hare-common-model" }
tonic = { workspace = true, features = ["codegen", "prost", "transport"] }
prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
