[package]
name = "hare-control-plane-model"
version = "0.1.0"
edition = "2021"

[dependencies]
hare-common-model = { path = "../hare-common-model" }
prost = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true, features = ["codegen"] }
tonic-prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
